--- # Bootstrap Webservers
- hosts: webservers
  tasks:
  - name: Git pull from remote repo
    block:
     - name: get stuff from git
       git:
         repo: https://github.com/aokugel/Django-Blog-Website.git
         dest: /home/ubuntu/projects/mysite
         clone: no
         update: yes
    become: true
    become_user: ubuntu
  - name: cycle services
    block:
    - name: cycle gunicorn
      service:
        name: gunicorn
        state: restarted
    - name: cycle nginx
      service:
        name: nginx
        state: restarted
    become: true
